version: "3.8"

x-env: &x-env
  env_file:
    - deploys/prod.env

services:
  movies:
    build:
      context: movie_admin
    volumes:
      - static:/static
    <<: *x-env
    depends_on:
      - postgres

  postgres:
    image: postgres:12.1
    restart: always
    <<: *x-env
    environment:
      POSTGRES_PASSWORD: devpass
    volumes:
      - devdb:/var/lib/postgresql/data

  nginx:
    image: nginx:1.19.2
    restart: always
    <<: *x-env
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx_sites:/etc/nginx/conf.d:ro
      - static:/static
    ports:
      - 8080:80
    depends_on:
      - movies

volumes:
  devdb:
  static: